export const ORDER_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  PREPARING: "PREPARING",
  READY_TO_SHIP: "READY_TO_SHIP",
  SHIPPING: "SHIPPING",

  CANCEL_REQUESTED: "CANCEL_REQUESTED",
  CANCELLED: "CANCELLED",

  RETURN_REQUESTED: "RETURN_REQUESTED",
  RETURNING: "RETURNING",
  RETURNED: "RETURNED",

  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;
