const filterConfig: Record<string, any[]> = {
  "VỢT CẦU LÔNG": [
    {
      key: "pricesRange",
      label: "Khoảng giá",
      type: "range",
      min: 1290000,
      max: 5099000,
    },
    {
      key: "sizes",
      label: "Size",
      type: "checkbox",
      options: ["3U", "3U-G5", "4U", "4U-G5", "4U-G6", "5U", "6U"],
    },
    {
      key: "colors",
      label: "Màu sắc",
      type: "checkbox",
      options: [
        "Cam",
        "Đen",
        "Đỏ",
        "Hồng",
        "Ngọc trai xám",
        "Tím",
        "Trắng",
        "Vàng",
        "Xanh",
      ],
    },
    {
      key: "materials",
      label: "Chất liệu",
      type: "checkbox",
      options: ["Graphite"],
    },
  ],
  "GIÀY CẦU LÔNG": [
    {
      key: "pricesRange",
      label: "Khoảng giá",
      type: "range",
      min: 990000,
      max: 1799000,
    },
    {
      key: "sizes",
      label: "Size",
      type: "checkbox",
      options: ["38", "39", "40", "41", "42"],
    },
    {
      key: "colors",
      label: "Màu sắc",
      type: "checkbox",
      options: ["Đen", "Trắng", "Xám"],
    },
    {
      key: "materials",
      label: "Chất liệu",
      type: "checkbox",
      options: ["Mesh", "Rubber", "Synthetic", "Synthetic Leather"],
    },
  ],
  "ÁO CẦU LÔNG": [
    {
      key: "pricesRange",
      label: "Khoảng giá",
      type: "range",
      min: 199000,
      max: 480000,
    },
    {
      key: "sizes",
      label: "Size",
      type: "checkbox",
      options: ["0.66mm", "0.70mm", "L", "M", "XL"],
    },
    {
      key: "colors",
      label: "Màu sắc",
      type: "checkbox",
      options: [
        "Cam",
        "Đen",
        "Đỏ",
        "Tím than",
        "Trắng",
        "Xám",
        "Xanh dương",
        "Xanh lá",
        "Xanh navy",
      ],
    },
    {
      key: "materials",
      label: "Chất liệu",
      type: "checkbox",
      options: [
        "Cotton Blend",
        "Dry-fit",
        "Nylon",
        "Polyester",
        "Polyester cao cấp",
        "Polyester co giãn nhẹ",
        "Polyester Dry-fit",
        "Polyester mềm nhẹ",
        "Polyester nhanh khô",
        "Polyester thoáng khí",
        "Vải mè thoáng khí",
        "Vải thể thao cao cấp",
        "Vải thể thao co giãn nhẹ",
        "Vải thể thao thoáng mát",
      ],
    },
  ],
  "QUẦN CẦU LÔNG": [
    {
      key: "pricesRange",
      label: "Khoảng giá",
      type: "range",
      min: 280000,
      max: 450000,
    },
    {
      key: "sizes",
      label: "Size",
      type: "checkbox",
      options: ["L", "M", "XL"],
    },
    {
      key: "colors",
      label: "Màu sắc",
      type: "checkbox",
      options: ["Xanh navy", "Đỏ", "Trắng"],
    },
    {
      key: "materials",
      label: "Chất liệu",
      type: "checkbox",
      options: ["Dry-fit", "Polyester", "Polyester Dry-fit"],
    },
  ],
  "VÁY CẦU LÔNG": [
    {
      key: "pricesRange",
      label: "Khoảng giá",
      type: "range",
      min: 59000,
      max: 249000,
    },
    {
      key: "sizes",
      label: "Size",
      type: "checkbox",
      options: ["5cm x 5m", "6-pack", "OneSize"],
    },
    {
      key: "colors",
      label: "Màu sắc",
      type: "checkbox",
      options: ["Bạc", "Đen", "Trắng", "Xanh"],
    },
    {
      key: "materials",
      label: "Chất liệu",
      type: "checkbox",
      options: ["Cotton Blend", "Elastic", "Feather", "Metal", "Nylon", "Synthetic"],
    },
  ],
  "TÚI VỢT CẦU LÔNG": [
    {
      key: "pricesRange",
      label: "Khoảng giá",
      type: "range",
      min: 990000,
      max: 1910000,
    },
    {
      key: "sizes",
      label: "Size",
      type: "checkbox",
      options: ["3U-G5", "4U-G5", "4U-G6", "39", "40", "41"],
    },
    {
      key: "colors",
      label: "Màu sắc",
      type: "checkbox",
      options: ["Đen", "Trắng", "Xám", "Xanh"],
    },
    {
      key: "materials",
      label: "Chất liệu",
      type: "checkbox",
      options: ["Graphite", "Mesh", "Rubber", "Synthetic Leather"],
    },
  ],
  "BALO CẦU LÔNG": [
    {
      key: "pricesRange",
      label: "Khoảng giá",
      type: "range",
      min: 520000,
      max: 1199000,
    },
    {
      key: "sizes",
      label: "Size",
      type: "checkbox",
      options: ["2 ngăn", "3 ngăn", "6 vợt", "28L", "30L", "32L"],
    },
    {
      key: "colors",
      label: "Màu sắc",
      type: "checkbox",
      options: ["Đen", "Xám", "Xanh", "Xanh ô liu"],
    },
    {
      key: "materials",
      label: "Chất liệu",
      type: "checkbox",
      options: ["Nylon", "Polyester", "PU"],
    },
  ],
  "PHỤ KIỆN CẦU LÔNG": [
    {
      key: "pricesRange",
      label: "Khoảng giá",
      type: "range",
      min: 89000,
      max: 1910000,
    },
    {
      key: "sizes",
      label: "Size",
      type: "checkbox",
      options: ["3U-G5", "4U-G5", "4U-G6", "39", "40", "41", "OneSize"],
    },
    {
      key: "colors",
      label: "Màu sắc",
      type: "checkbox",
      options: ["Đen", "Trắng", "Xám", "Xanh"],
    },
    {
      key: "materials",
      label: "Chất liệu",
      type: "checkbox",
      options: [
        "Cotton Blend",
        "Graphite",
        "Mesh",
        "Nylon",
        "Rubber",
        "Synthetic",
        "Synthetic Leather",
      ],
    },
  ],
};

export default filterConfig;
