export const CLASS_ENROLLMENT_STATUS = Object.freeze({
  OPEN: "OPEN",
  LOCKED: "LOCKED",
  ENDED: "ENDED",
});

export const ENROLLMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
});

export const ENROLLMENT_SOURCE = Object.freeze({
  POST_REGISTER: "POST_REGISTER",
  COACH_MANUAL: "COACH_MANUAL",
});

export const CLASS_NOTIFICATION_TYPE = Object.freeze({
  ENROLLMENT_REQUEST: "CLASS_ENROLLMENT_REQUEST",
  ENROLLMENT_APPROVED: "CLASS_ENROLLMENT_APPROVED",
  ENROLLMENT_REJECTED: "CLASS_ENROLLMENT_REJECTED",
  CLASS_BROADCAST: "CLASS_BROADCAST",
});
