export const COACH_APPLICATION_STATUS = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
});

export const COACH_APPLICATION_NOTIFICATION = Object.freeze({
  NEW_REQUEST: "COACH_APPLICATION_NEW",
  APPROVED: "COACH_APPLICATION_APPROVED",
  REJECTED: "COACH_APPLICATION_REJECTED",
});
