export const COMMENT_REPORT_REASON = Object.freeze({
  SPAM: "SPAM",
  OFFENSIVE: "OFFENSIVE",
  UNAUTHORIZED_AD: "UNAUTHORIZED_AD",
  HARASSMENT: "HARASSMENT",
  OTHER: "OTHER",
});

export const COMMENT_REPORT_STATUS = Object.freeze({
  PENDING: "PENDING",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
});

export const COMMENT_REPORT_AUTO_HIDE_THRESHOLD = 3;

export const COMMENT_REPORT_REASON_LABEL = Object.freeze({
  [COMMENT_REPORT_REASON.SPAM]: "Spam",
  [COMMENT_REPORT_REASON.OFFENSIVE]: "Ngôn từ xúc phạm",
  [COMMENT_REPORT_REASON.UNAUTHORIZED_AD]: "Quảng cáo trái phép",
  [COMMENT_REPORT_REASON.HARASSMENT]: "Quấy rối",
  [COMMENT_REPORT_REASON.OTHER]: "Khác",
});
