export const SUPPLIER_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
});

export const PURCHASE_RECEIPT_STATUS = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
});

export const STOCK_ITEM_TYPE = Object.freeze({
  PRODUCT_VARIANT: "PRODUCT_VARIANT",
  BEVERAGE: "BEVERAGE",
});

export const STOCK_TRANSACTION_TYPE = Object.freeze({
  IMPORT: "IMPORT",
  SALE: "SALE",
  CANCEL_ORDER: "CANCEL_ORDER",
  RETURN: "RETURN",
  ADJUSTMENT: "ADJUSTMENT",
});

export const STOCK_REFERENCE_TYPE = Object.freeze({
  PURCHASE_RECEIPT: "PURCHASE_RECEIPT",
  ORDER: "ORDER",
  ADJUSTMENT: "ADJUSTMENT",
});
