export const PAYMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
  REFUNDED: "REFUNDED",
});

export const PAYMENT_METHOD_STATUS = Object.freeze({
  COD: "COD",
  VNPAY: "VNPAY",
  WALLET: "WALLET",
});

export const WALLET_TRANSACTION_TYPE = Object.freeze({
  DEPOSIT: "DEPOSIT",
  PAYMENT: "PAYMENT",
  REFUNDED: "REFUNDED",
  WITHDRAW: "WITHDRAW",
});

export const TARGET_PAYMENT_TYPE = Object.freeze({
  ORDER: "ORDER",
  BOOKING: "BOOKING",
  WALLET_TOPUP: "WALLET_TOPUP",
});

export const WALLET_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  LOCKED: "LOCKED",
});

export const WALLET_TRANSACTION_STATUS = Object.freeze({
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});

export const WITHDRAW_REQUEST_STATUS = Object.freeze({
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});
