export const ROLE_IN_SHIFT = Object.freeze({
  CASHIER: "CASHIER",
  STAFF: "STAFF",
});

export const WORK_SHIFT_STATUS = Object.freeze({
  SCHEDULED: "SCHEDULED",
  INPROGRESS: "INPROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
});
